---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Initialise Packages

```{r}
{
  require(lme4)
  require(ggplot2)
  require(tidyverse)
  require(dplyr)
  require(cowplot)
  require(writexls)
  require(tidyr)
  require(openxlsx)
}
```

# Set working directory
setwd('C:/Users/Antonio/OneDrive - University College London/Desktop/DataLab4')

```{r}
# Load data

 data <- data.frame()
  for (blk in 9) #1:8){
    filName <- sprintf("Detection_%1.0f.xlsx", blk)
    rep <- read.xlsx(xlsxFile = filName, sheet = 1, colNames = TRUE)
    rep$blkCode <- blk
    data <- rbind(data, rep)
```


```{r}
# Preprocess raw data
{
  rawData <- data %>%
    filter(!is.na(Experiment.ID)) %>%                     # Filter out NA
    group_by(Participant.Private.ID) %>%                  # Renumber participants
    mutate(partID = cur_group_id()) %>%
    group_by(partID, staircase) %>%                       # Create staircase trial number
    mutate(stairTrialNr = 1,
           stairTrialNr = cumsum(stairTrialNr),
           laggedResp = lag(response,1L),                 # Add lagged resp to count reversals
           reversal = 0,                                  # Add reversals column
           reversal = (response != laggedResp) * 1,       # Find reversals
           reversal = (replace_na(reversal, 0)),          # Remove NA from reversals
           revNr = cumsum(reversal))                      # Count number of reversals for each staircase
}
```


```{r}
# Average 4 last reversals
{
  revData <- rawData %>%
    filter(revNr > 3 & reversal != 0) %>%                                            # Take first occurrence of 4 last reversals
    group_by(partID, staircase) %>%
    summarise(meanPWM = mean(buzz_pcnt)) %>%                                         # Average
    mutate(nRows = row_number(),
           maxRows = max(nRows)) %>%
    filter(maxRows == 2) %>%
    mutate(staircase = str_replace(as.character(staircase), "0", "Ascending"),       # Change names of staircases
          staircase = str_replace(as.character(staircase), "1", "Descending")) %>%
    select(-c('maxRows', 'nRows')) %>%                                               # Remove unnecessary columns
    spread(staircase, meanPWM) %>%                                                   # Spread in wide format
    mutate(Convergence = abs(Ascending-Descending)) %>%                              # Calculate convergence
    filter(Convergence < .25) %>%                                                    # Remove participants with poor convergence
    mutate(aveRev = (Ascending + Descending)/2)                                      # Calculate staircases average

  meanRev = mean(revData$aveRev)
  stdRev = sd(revData$aveRev)
}
```


```{r}
#Find good and bad devices/os/browsers
{
  goodPart <- revData$partID

  devData <- rawData %>%
    group_by(partID) %>%
    summarise(Device = unique(Participant.Device),
              Os = unique(Participant.OS),
              Browser = unique(Participant.Browser)) %>%
    mutate(goodData = (partID %in% goodPart) * 1) %>% 
    left_join(revData)
}

{clipr::write_clip(devData)}
```


```{r}
#Plot staircases
{
  Det_allStaircases <- ggplot(rawData, aes(x = stairTrialNr, y = buzz_pcnt*100, color = as.factor(staircase))) + 
    geom_line() +
    facet_wrap(partID ~.)+
    scale_color_manual(values = c('green2', 'red2'), name = 'Staircase', labels = c('Ascending', 'Descending')) + 
    scale_y_continuous(name = 'Duty cycle (%)') + 
    scale_x_continuous(name = 'Trial number')
  ggsave("Lab4_Detection_All_Staircases_2023.tiff", width = 16, height = 8)  
}

Det_allStaircases
```


```{r}
#Plot good staircases
{
  Det_goodStaircases <- ggplot(goodData, aes(x = stairTrialNr, y = buzz_pcnt*100, color = as.factor(staircase))) + 
    geom_line() +
    #facet_wrap(partID ~.) +
    facet_wrap(Participant.Device ~ partID) +
    scale_color_manual(values = c('green2', 'red2'), name = 'Staircase', labels = c('Ascending', 'Descending')) + 
    scale_y_continuous(name = 'PWM Duty cycle (%)') + 
    scale_x_continuous(name = 'Trial number')
  ggsave("Lab4_Detection_Good_Staircases.tiff", width = 16, height = 8)  
}

Det_goodStaircases
```


```{r}
#Plot bad staircases
{
  Det_badStaircases <- ggplot(badData, aes(x = stairTrialNr, y = buzz_pcnt*100, color = as.factor(staircase))) + 
    geom_line() +
    #facet_wrap(partID ~.) +
    facet_wrap(Participant.Device ~ partID) +
    scale_color_manual(values = c('green2', 'red2'), name = 'Staircase', labels = c('Ascending', 'Descending')) + 
    scale_y_continuous(name = 'PWM Duty cycle (%)') + 
    scale_x_continuous(name = 'Trial number')
  ggsave("Lab4_Detection_Bad_Staircases.tiff", width = 16, height = 8)  
}

Det_badStaircases

```

